spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xdl-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  session:
    store-type: none
  redis:
    host: localhost
    port: 6379
    password: 123456

server:
  port: 8060

security:
  basic:
    enabled: false

