spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.43.130:3306/xdl-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  session:
    store-type: none
  redis:
    host: 192.168.43.130
    port: 6379
    password:

server:
  port: 8060

#security:
#  basic:
#    enabled: false

xdl:
  security:
    browser:
      loginType: JSON
#      loginPage: /demo-signIn.html
    code:
      image:
        width: 100
        length: 4
#        url: /user,/user/*

